name: API Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'services/**'
      - 'packages/**'
      - 'tests/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'services/**'
      - 'packages/**'
      - 'tests/**'
      - '.github/workflows/api-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Lint
      run: yarn turbo run lint:changed
    
    - name: Type check
      run: yarn turbo run typecheck:changed
    
    - name: Unit tests
      run: yarn turbo run test:changed
    
    - name: Integration tests
      run: yarn turbo run test:integration:changed
    
    - name: Build packages
      run: yarn turbo run build:changed
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
